Add example using traits
blinking8888/atticus pull request #6
Opened 2023-07-15 00:48 UTC by LorenzoLeonardo

Added an example using traits

2023-07-15 05:02 UTC, blinking8888 requested changes
Let's have the example in 1 file i.e. `examples/car.rs` and let's have the examples be shorter or more concise.

2023-07-15 15:09 UTC, blinking8888 commented on examples/with_traits/main.rs
> +async fn run_car(car: CarKind) {
Let's move car.rs under `examples` and not anymore inside `examples/with_traits`

2023-07-15 21:18 UTC, LorenzoLeonardo commented on examples/with_traits/main.rs
> +async fn run_car(car: CarKind) {
Done

2023-07-16 00:59 UTC, blinking8888 commented on examples/with_traits/main.rs
> +async fn run_car(car: CarKind) {
lgtm

2023-07-16 01:01 UTC, blinking8888 approved these changes
lgtm

2023-07-16 01:01 UTC, merged